sudo: required
services: 
    - docker

before_install:
    - docker build -t istiaquem/docker-react -f Dockerfile.dev .

script:
     - docker run istiaquem/docker-react npm run test -- --coverage  
deploy:
     provide: elasticbeanstalk
     region: "us-east-2"
     app: "docker-react"
     env : "DockerReact-env"
     bucket_name: "elasticbeanstalk-us-east-2-182099387343"
     bucket_path: "docker-react"

on: 
   branch: master
